import Foundation

/// One durable home for everything the app knows about a song.
///
/// Practice state and analysis results both belong to the *song*, not to a
/// separation of it. Re-separating with a different model produces a new
/// `Tracks/<id>/` folder, so anything kept there would be lost with the old one
/// — which is exactly what used to happen to practice settings, keyed by track
/// ID in `UserDefaults`. Both now live beside the **original**, keyed by
/// original ID, and survive every re-separation.
///
/// Writes go through `LibraryMetadata`, whose encode-and-replace is atomic, so
/// a process killed mid-write leaves the previous file rather than a truncated
/// one. Reads are deliberately non-throwing: a damaged result is a missing
/// result, never a reason a song cannot be opened.
struct SongStorage: Sendable, Equatable {
    static let practiceFilename = "practice.json"
    static let lyricsFilename = "lyrics.json"
    static let chordsFilename = "chords.json"
    static let beatsFilename = "beats.json"

    /// What the analysis phases compute. Practice state is deliberately not one
    /// of them: it is the user's own work, and no algorithm improvement can
    /// make it stale.
    static let analysisFilenames = [lyricsFilename, chordsFilename, beatsFilename]
    static let songFilenames = analysisFilenames + [practiceFilename]

    let folderURL: URL
    /// True when the original has been deleted and this song's state has to
    /// live in the separation's own folder instead. It then dies with that
    /// separation, which is the honest outcome: there is no longer a song for
    /// it to outlive.
    let isFallback: Bool

    init(folderURL: URL, isFallback: Bool = false) {
        self.folderURL = folderURL
        self.isFallback = isFallback
    }

    /// Resolves a song's storage from its separation, preferring the original.
    static func resolve(
        originalID: UUID?,
        trackFolder: URL,
        originalsRoot: URL? = nil
    ) -> SongStorage {
        if let originalID,
           let folder = originalFolder(for: originalID, root: originalsRoot) {
            return SongStorage(folderURL: folder)
        }
        return SongStorage(folderURL: trackFolder, isFallback: true)
    }

    /// The original's folder, or `nil` when it has been deleted. Never created
    /// on demand: a folder conjured here would be an `Originals` entry with no
    /// audio in it, which every discovery pass would then have to learn to
    /// ignore.
    static func originalFolder(for originalID: UUID, root: URL? = nil) -> URL? {
        guard let root = root ?? (try? LibraryStaging.libraryRoot(named: "Originals")) else {
            return nil
        }
        let folder = root.appendingPathComponent(originalID.uuidString, isDirectory: true)
        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(atPath: folder.path, isDirectory: &isDirectory),
              isDirectory.boolValue else { return nil }
        return folder
    }

    func url(for filename: String) -> URL {
        folderURL.appendingPathComponent(filename)
    }

    func read<T: Decodable>(_ type: T.Type, from filename: String) -> T? {
        try? LibraryMetadata.read(type, from: url(for: filename))
    }

    func write<T: Encodable>(_ value: T, to filename: String) throws {
        try FileManager.default.createDirectory(
            at: folderURL,
            withIntermediateDirectories: true
        )
        try LibraryMetadata.write(value, to: url(for: filename))
    }

    func remove(_ filename: String) {
        try? FileManager.default.removeItem(at: url(for: filename))
    }

    /// What this song's own data costs, separately from the audio it describes.
    /// Storage accounting reports it as its own line because it is the only
    /// part of a library folder the user cannot see the size of by ear.
    static func songDataByteCount(of folder: URL) -> Int64 {
        songFilenames.reduce(0) { total, filename in
            total + LibraryStaging.byteCount(of: folder.appendingPathComponent(filename))
        }
    }

    // MARK: - Backup

    /// One backup rule for the whole original folder, decided here rather than
    /// inherited file by file.
    ///
    /// The rule has to say two things because the folder now holds two kinds of
    /// thing. The downloaded audio is reproducible cache — it can be fetched
    /// again from its source URL — so it is excluded, which is what keeps a
    /// library of songs out of the user's iCloud quota. Everything else in the
    /// folder is the user's own work: practice settings they tuned, loops they
    /// set, corrections they made to an analysis. None of that can be
    /// regenerated by anything, so it is backed up. The folder itself is
    /// therefore never excluded as a whole.
    static func applyBackupPolicy(to folder: URL, audioFilename: String) {
        var audioURL = folder.appendingPathComponent(audioFilename)
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        try? audioURL.setResourceValues(values)
    }

    // MARK: - Legacy defaults

    /// Keys earlier builds wrote per song. Pre-release, so there is nothing to
    /// migrate — but without a sweep they would sit in the defaults database
    /// forever, and "no per-song state remains in `UserDefaults`" would be true
    /// only of code and not of disk.
    static let legacyPerSongDefaultsPrefixes = ["practiceSettings.v1.", "stemLevels."]

    static func purgeLegacyPerSongDefaults(_ defaults: UserDefaults = .standard) {
        for key in defaults.dictionaryRepresentation().keys
        where legacyPerSongDefaultsPrefixes.contains(where: key.hasPrefix) {
            defaults.removeObject(forKey: key)
        }
    }
}

/// Something an analysis phase computes and caches beside the song.
///
/// `analysisVersion` is the analysis counterpart of `separationCacheVersion`:
/// improving an algorithm makes every result the old one produced wrong, and
/// bumping the constant is what makes the app recompute rather than display
/// stale output. Nothing branches on the value — a result at a version we no
/// longer produce is discarded, not migrated.
protocol AnalysisArtifact: Codable, Sendable {
    /// The version this build produces.
    static var currentAnalysisVersion: Int { get }
    static var filename: String { get }
    /// The version the stored result was produced at.
    var analysisVersion: Int { get }
}

extension SongStorage {
    func readAnalysis<T: AnalysisArtifact>(_ type: T.Type) -> T? {
        guard let value = read(type, from: T.filename),
              value.analysisVersion == T.currentAnalysisVersion else { return nil }
        return value
    }

    func writeAnalysis<T: AnalysisArtifact>(_ value: T) throws {
        try write(value, to: T.filename)
    }
}
